//con la extesnion Client Rest podemos probar a hacer request en nuestro propio proyecto. 
//De esta forma cualquier persona puede hacer las request desde el propio proyecto
// Para que funcione pulsamos donde pone Send Request. Ej: 

GET http://localhost:3000/api/movies