//Otra forma de poner el post un json en vez de usar insomnia o postman
//es usar este formato donde hay que especificar el content-type y luego
//mas abajo poner el objeto en formato json 
//Nota, también se puede agregar varias solicitudes en el mismo archivo usando ###separadores:

POST   http://localhost:3000/products
Content-Type: application/json

 {     
      "name": "leather sofa adfa",
      "image":
        "https://dl.airtable.com/.attachments/3245c726ee77d73702ba8c3310639727/f000842b/product-5.jpg",      
      "price": 9.99,
      "desc":"I'm baby direct trade farm-to-table hell of"
    }

###

GET  http://localhost:3000/test

